# tag repo digest=sha256:f3af90f9fd33109f9a96a659d9bcb8d186b8bba88ced3ec167a133ab69c3e119 corresponds to tag 'latest' on 13.04.2024
FROM jenkins/inbound-agent@sha256:f3af90f9fd33109f9a96a659d9bcb8d186b8bba88ced3ec167a133ab69c3e119

USER root

# Install Python 3 and tools
RUN apt-get update
RUN apt-get install -y python3.11 python3.11-dev python3.11-distutils python3-pip
RUN apt install -y python3-pytest python3-flake8 pylint python3-mypy

CMD /usr/bin/bash

USER jenkins
